### PR TITLE
Modal Refactor to CSSTransitionGroup

### PR DESCRIPTION
**Pull request by KeKs0r**
I wanted to use the Modal, but in its current version somehow it was always visible, since the visibility depended on showModal state, which was automatically.

I have also refactored it to ReactCSSTransitionGroup for Animations. In order to access the default animations of Touchstone I have taken them from "createApp" into an extra mixin, which can now be used by anyone in any other component, if they want to "animate" things with touchstone animations.

I also added the possibility to provide the content of the Modal as child props, which should make it especially for more complex HTML or JSX more comfortable to provide content to the modal.

### CODE REVIEW

**Comment by KeKs0r** [comment]
Any Feedback on this? If you don't like the animation things I can also solve it differently but currently the modals are somewhat "unusable" because they always show and you cant define easily more complex content (which would be done via the "children" props)

**Comment by dcousens** [comment]
@jossmac can you shed some light on whether this is worthwhile?

**Comment by dcousens** [comment]
bump @jossmac

**Comment by dcousens** [comment]
Closing in favour of #64

**Pull request closed without merging**
