### PR TITLE
Compatibility with React 0.13

### PR DESCRIPTION
**Pull request by cassiozen**

### CODE REVIEW

**Comment by dcousens** [comment]
Somehow I don't think this is all that will need to be changed.

**Comment by cassiozen** [comment]
Hi @dcousens, this was the bare minimum to run under react 0.13, but I agree there are more things that need to change to fully work with idiomatic React 0.13 (e.g. mixins)

**Comment by dcousens** [comment]
@JedWatson can you look over this?  I'll test/merge it later, but just a once over would be greatly appreciated.

**Comment by JedWatson** [comment]
Thanks @cassiozen, I'm going to manually merge this (due to conflicts) and make sure everything works now, high time we got over the 0.13 hurdle.

**Pull request closed without merging**
