### PR TITLE
React 14

### PR DESCRIPTION
**Pull request by vinceprofeta**

### CODE REVIEW

**Comment by vinceprofeta** [comment]
@JedWatson this was my pass at updating to react 14. In my project I changed the build process to use Webpack rather than the touchstone-tasks and the update to 14 works great. Browserify still seems to have an issue with using reactDom, see the error below:

Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner)."

I am not very familiar with Browserify and saw in a post that you have seen and been able to resolve the issue. If you could help me out on that front that would be great.

Lastly, React 14 cssTransitionGroup now requires transition timeouts, which when added mess up page transitions. For the time being I left them out.

**Comment by pke** [comment]
The culprit is "react-dom". It pulls in another version of "react" into the bundle. But I have no clue how to prevent that.

**Comment by thiagofelix** [comment]
@vinceprofeta great works!

Have you updated the started project as well? Where are the changes regarding the webpack and browserify that you mentioned in the PR?

**Comment by vinceprofeta** [comment]
@thiagofelix I started to update the starter project. I will post that soon. Its worth noting that the Webpack changes I made were to replace the need for touchstone tasks in the starter, which is in a separate private project I have. I wanted to change the way the files were structured to match a pattern that fits my preference and I was not sure how to do that using Gulp and Browserify. It doesnt seem to make sense to include the webpack configuration into a PR for the starter. 

@pke I think @JedWatson might have insight on how to fix that issue.

**Comment by vinceprofeta** [comment]
@thiagofelix @pke 

Here is the starter I updated 
https://github.com/vinceprofeta/touchstonejs-starter/tree/react-14

Again react-dom issue persists, also be aware that the package JSON points to my forked branch of touchstone

**Comment by dcousens** [comment]
Great work @vinceprofeta  :+1: ,  I have no idea which one to accept yet (#96 or #97).

**Comment by dcousens** [comment]
What is with the file permission changes?

**Comment by pke** [comment]
@vinceprofeta The react-dom issue is easily solved by replacing the `react/addons` exclusion in the gulpfile with `react-dom`.

**Comment by vinceprofeta** [comment]
@pke I can make those changes. @dcousens Im not quite sure why/how their were permission changes. @thiagofelix your PR seems to do the same thing? Did you fix the react-dom issue in the gulp file?

**Comment by thiagofelix** [comment]
Hi guys. @vinceprofeta @pke 

I didn't change the gulpfile, I think it should be a different PR since it is a different repo.

The PR I made is really for the library, not the starter neither the gulp tasks.

**Comment by JedWatson** [comment]
Thanks for the PR @vinceprofeta - I've merged #97 because it's slightly cleaner as a PR, but really appreciate the work you put into this. Hoping to have a react 0.14 compatible version out today :)

**Pull request closed without merging**
