### PR TITLE
Add a new DatePicker component and improve the Popup component.

### PR DESCRIPTION
**Pull request by supnate**
1. Add DatePicker, DatePickerPopup components.
2. Add LabelValue component, used as the field of DatePickerPopup in a form.
3. Improve Popup component: now it could be arbitrary width.

### CODE REVIEW

**Comment by supnate** [comment]
As mentioned earlier, I created a DatePicker for my own project and I think it may be also useful for other TouchstoneJS users. Since that I don't see any i18n solutions in TouchstoneJS so I can just use hard-coded i18n strings in the component.

**Comment by supnate** [comment]
@jossmac Any comment?

**Comment by jossmac** [comment]
Looks good @supnate thanks for this!

**Comment by supnate** [comment]
@jossmac Thank you!

**Comment by JorritPosthuma** [comment]
Is it possible to publish a 0.5.1 to npm? The https://github.com/touchstonejs/touchstonejs-starter doesn't have these components

**Comment by JedWatson** [comment]
@JorritPosthuma done; we bumped to 0.6.0 because of a potentially breaking change where `.views` is no longer exposed.

**Pull request merged**
